
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /


tze_api:
    resource: "@ApiBundle/Ressources/config/routing/api.yml"
    prefix:   /api


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"